### ISSUE TITLE
Error generating bindings- Could not find type 'Point' in namespace 'Windows.Foundation'

### ISSUE THREAD

**Issue by paytondevs** [thebrowsercompany/windows-samples#1]
Hello,
I am trying to compile the sample app on Windows 11 (Insider) 22H2 build 23536.1000, and I am getting the following error while generating bindings:
`swiftwinrt : error Could not find type 'Point' in namespace 'Windows.Foundation'`
This feels like a swiftwinrt error, but I was told to put it here. I'd be happy to provide any extra information. 
Thanks!

**Comment by stevenbrix** [comment]
thanks @paytontech! i think this issue is due to a missing windows sdk. you should have 10.0.20348.0 installed. i realize this isn't in the pre-requisites.

**Comment by hironichu** [comment]
Well that fixes the prebuild, however the following step doesnt work... 

![image](https://github.com/thebrowsercompany/windows-samples/assets/64388064/d1330943-4471-4231-b59f-53f23bf954e4)

**Comment by paytondevs** [comment]
yup! problem solved. thank you!

**Comment by paytondevs** [comment]
> Well that fixes the prebuild, however the following step doesnt work...
> 
> ![image](https://user-images.githubusercontent.com/64388064/279211000-d1330943-4471-4231-b59f-53f23bf954e4.png)

i'm having the exact same issue

**Comment by stevenbrix** [comment]
@paytontech this should be fixed now! please file an issue if you're having more problems
