### ISSUE TITLE
Microsoft.WindowsAppRuntime.Bootstrap.dll could not be found

### ISSUE THREAD

**Issue by stefanspringer1** [thebrowsercompany/windows-samples#10]
When starting WinUI3AnimationsPreview.exe, I get a message that Microsoft.WindowsAppRuntime.Bootstrap.dll could not be found. When building, there is a message that Microsoft.WindowsAppRuntime.Bootstrap.dll is being copied.

**Comment by oskargargas** [comment]
@stefanspringer1 take a look at: https://github.com/thebrowsercompany/windows-samples/issues/5#issuecomment-1870159426

**Comment by stefanspringer1** [comment]
I made the error of looking at the message `Linking C:\Projekte\windows-samples\build\spm\x86_64-unknown-windows-msvc\debug\WinUI3AnimationsPreview.exe`, and could not start from there, but as documented the README , it should be started from `windows-samples\build\bin`. Sorry for not reading your documentation more carefully!

(A way to find the Microsoft.WindowsAppRuntime.Bootstrap.dll manually is to see what command `cmake --preset debug` outputs:

```
Added package 'Microsoft.WindowsAppSDK.1.4.231008000' to folder 'C:\Projekte\windows-samples\build\NugetPackages'
````

I could find the Bootstrap DLL in `C:\Projekte\windows-samples\build\NugetPackages\Microsoft.WindowsAppSDK.1.4.231008000\runtimes\win10-x64\native`, but as I already noted, your process works fine.)

_Please close the issue._ Thanks!
