### ISSUE TITLE
`print` doesn't work when running app via LLDB (via VSCode)

### ISSUE THREAD

**Issue by oskargargas** [thebrowsercompany/windows-samples#11]
Have some time to play with Swift on Windows during Christmas. Managed to get app start from VSCode. Can debug it via LLDB. But there still is one minor annoyance. When I run app using LLDB there is no `stdout/print` output. It is visible if I run binary directly from terminal so I know that everything compiles correctly. The problem is with LLDB or lunch configuration.

Launch config:
```json
{
  "type": "lldb",
  "request": "launch",
  "name": "lldb",
  "program": "${workspaceFolder}/build/bin/${workspaceFolderBasename}",
  "args": [],
  "cwd": "${workspaceFolder}",
  "preLaunchTask": "Build"
}
```

CodeLLDB LLDB library path:
`C:\Users\xxx\AppData\Local\Programs\Swift\Toolchains\0.0.0+Asserts\usr\bin\liblldb.dll`

I use a workaround - build, run from command line, attach debugger using separate task. It's usable but would be nicer if it was single keystroke.

```json
{
  "name": "attach lldb",
  "type": "lldb",
  "request": "attach",
  "program": "${workspaceFolder}/build/bin/${workspaceFolderBasename}"
}
```

**Comment by stevenbrix** [comment]
yeah this is a known issue with swift, you need to follow the `print` up with an `fflush(stdout)`
