### ISSUE TITLE
Unable to build due to "too many exported symbols"

### ISSUE THREAD

**Issue by Noemata** [thebrowsercompany/windows-samples#22]
Build failed, here's the output:

Fetching https://github.com/thebrowsercompany/swift-windowsappsdk
Fetched https://github.com/thebrowsercompany/swift-windowsappsdk from cache (1.12s)
Fetching https://github.com/thebrowsercompany/swift-windowsfoundation
Fetched https://github.com/thebrowsercompany/swift-windowsfoundation from cache (0.63s)
Fetching https://github.com/thebrowsercompany/swift-winui
Fetched https://github.com/thebrowsercompany/swift-winui from cache (0.84s)     
Fetching https://github.com/thebrowsercompany/swift-cwinrt
Fetched https://github.com/thebrowsercompany/swift-cwinrt from cache (0.99s)    
Building for debugging...
[1/1] Planning build
Building for debugging...
lld-link: error: too many exported symbols (got 67393, max 65535)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1/11] Linking D:\Swift_with_WinUI\windows-samples\.build\x86_64-unknown-wind…  

Please advise.

**Comment by tristanlabelle** [comment]
The Swift package manager has design limitation that causes it to export every public symbol on Windows binaries, and Windows has a hard 65535 limit on those. As a workaround, libraries can be build as dlls to spread the symbols. Even with this workaround, we found that we couldn't build a large application using it, which is why you're seeing uses of CMake elsewhere.

Also, we are not actively maintaining these repos and may remove them since they are far behind what we use internally. A more robust approach would be to use swift-winrt directly to generate the APIs you need, though this is certainly more involved.

**Comment by Noemata** [comment]
Thanks for the reply.  I really do need to get this going.  I did look at your swift-winrt repo under your account.  Would appreciate some hints on moving this forward.  So there's no chance to have pre-built packages that work with package manager in some fashion?  I really like the concept of using Swift on windows.  I'm hoping it's a better alternative to both Rust and C# where performance and security are key considerations.  There are a quite a number of reasons to stay away from C#.  Thank you for the quick reply.  Would appreciate any hints you can provide.  I also have some ideas for your browser initiative, just in case you folks want to get to financial viability faster.

**Comment by tristanlabelle** [comment]
The Swift package manager does not support pre-built packages on Windows, you have to consume from source. Our pregenerated projections repos are quite outdated at this point, and not set up to be regenerated easily (I'll consider removing/archiving them altogether).

`thebrowsercompany/swift-winrt` is our battle-tested WinRT projections generator that we use in Arc. It looks like we're not publishing the builds publicly, but you can build it locally and use the executable to generate the projections that you need, check those into a repo, and consume them using SPM (so long as you're generating an amount of projections that won't run into the SPM exports limitation). We don't have much guidance on doing this unfortunately, but hopefully it's fairly straightforward.

`tristanlabelle/swift-winrt` is an independent personal project of mine for a Swift implementation of a WinRT projections generator. It is experimental and has not been used in any real application. If you want to try it, we can discuss it over there separately.

I'll resolve this issue as I've explained the SPM limitation. You're welcome to open other issues if you encounter specific problems, or use the discussion tab for more conversation.

**Comment by Noemata** [comment]
@tristanlabelle  I see.  Makes sense.  Drag.  I just started with Swift on Windows, so I'm more than a little naive about the details.  Thank you for the clarification.  So much for getting a free lunch.  SPM would have made this easy.  I'm quite intrigued by what your company is doing.  I really like the idea of using Swift on Windows.  I had my own reasons for choosing it over Rust.  C# performance issues seem to be insurmountable, unless you opt for a combination of native and AOT.  I am curious why you folks opted for Swift on Windows.  I'm guessing it's mostly about retaining code continuity across platforms?  Lastly, it would be helpful to get a simpl(ish) working sample using thebrowsercompany/swift-winrt.  Just to see the strategy that's used for pruning out needed projections.  Thanks again.

**Comment by tristanlabelle** [comment]
> Lastly, it would be helpful to get a simpl(ish) working sample using thebrowsercompany/swift-winrt.

This is what this repository is supposed to be. Unfortunately it might be outdated or only build with some Swift toolchains and we don't have much capacity to update it at the moment.

**Comment by Noemata** [comment]
Thanks for the clarification.  I have already decided not to consider this option further.  You are 100% correct, the toolchain is too dated to be viable.  Suggest you archive associated repos.  This work is only useful from a conceptual perspective.

**Comment by tristanlabelle** [comment]
That's a fair call, I'll take the action item. Thanks!
